### ISSUE TITLE
Classe faltando?

### ISSUE THREAD

**Issue by pdraguiar** [andersontaraujo/music-application#1]
Anderson, acredito que esteja faltando comitar a classe QMusica utilizada na MusicaRepositoryImpl.java, confere?

**Comment by andersontaraujo** [comment]
Ah, é porque essa classe é gerada no build do Maven. Esqueci de mencionar isso. No caso, ela é gerada pelo QueryDSL, um dependência, que nem acontece com os stubs de WADL que gerávamos no projeto. Após rodar o Maven, essa classe vai estar no diretório target/generated-sources/java/...
